import type { Metadata } from "next";
import { Sidebar } from "../user/components";
import MainLayout from "@/app/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Dashboard.User",
  description: "Generated by create next app",
};

export default function Userlayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <MainLayout>
        <div className="grid md:grid-cols-3 col-span-1">
          <div className="col-span-1 bg-white py-10 md:block hidden">
            <Sidebar />
          </div>
          <div className="md:col-span-2 col-span-1 py-10 bg-[rgb(243,244,248)] w-full overflow-auto">{children}</div>
        </div>
      </MainLayout>
    </>
  );
}
